config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :searches, only: [:create]
      resources :users, only: [:index, :show, :create]
    end
  end
  resources :users, only: [:index, :show]
  get 'tiny_urls/show'
  get 'find_expert', to: 'api/v1/searches#find_expert' # find_expert_path
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expertise.rb
class Expertise < ApplicationRecord
  belongs_to :user
  validates :website_text, presence: true, uniqueness: { scope: :user_id }
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, :class_name => 'User'

  validates_presence_of :user_id
  validates_presence_of :friend_id
end

app/models/search.rb
class Search < ApplicationRecord
  validates_presence_of :search_text
end

app/models/tiny_url.rb
class TinyUrl < ApplicationRecord
  TINY_URL_LENGTH = 7

  validates :original_url, presence: true, format: {
    with: /\A(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?\z/i,
    message: "Invalid url"
  }

  before_create :generate_shortened_url
  before_create :sanitize_url

  scope :with_shortened_url, -> (url) { where(shortened_url: url) }

  def create_tiny_url
    url = 'http://' +half_url_sample + '.' + half_url_sample
  end

  private
  def half_url_sample
    ([*('a'..'z'),*('0'..'9')]).sample(TINY_URL_LENGTH/2).join
  end

  def generate_shortened_url
    url = create_tiny_url
    url_already_present = TinyUrl.with_shortened_url(url).first
    if url_already_present
      generate_shortened_url
    else
      self.shortened_url = url
    end
  end

  def sanitize_url
    sanitized_url = self.original_url.gsub(/(https?:\/\/)|(www\.)/, '')
    self.sanitized_url = "http://#{sanitized_url}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_validation :create_tiny_url, if: -> { !tiny_url }

  validates :name, presence: true
  validates :url, presence: true
  validates :tiny_url, presence: true

  has_many :friendships
  has_many :friends, through: :friendships
  has_many :expertise, dependent: :destroy

  before_destroy :remove_old_friendships

  attr_reader :sanitized_url

  def add_friend(friend)
    Friendship.create(user_id: id, friend_id: friend.id)
    Friendship.create(user_id: friend.id, friend_id: id)
  end

  def create_tiny_url
    tiny_url = TinyUrl.find_or_create_by(original_url: self.url)
    @sanitized_url = tiny_url.sanitized_url
    self.tiny_url = tiny_url.shortened_url
  end

  def is_friend?(friend)
    if friend.class == User
      Friendship.exists?(user_id: id, friend_id: friend.id)
    elsif friend.class == Integer
      Friendship.exists?(user_id: id, friend_id: friend)
    end
  end

  private

  def remove_old_friendships
    Friendship.where("user_id = ? OR friend_id = ?", id, id).destroy_all
  end
end

app/controllers/api/api_controller.rb
class Api::ApiController < ApplicationController
  skip_forgery_protection
end

app/controllers/api/v1/searches_controller.rb
class Api::V1::SearchesController < Api::ApiController
  def create
    search = Search.new(search_params)
    if search.save
      render json: search, status: 200
    else
      render json: { errors: search.errors.full_messages }, status: 400
    end
  end

  def find_expert
    if Search.create(search_text: permitted_params[:search]) && user = User.find(permitted_params[:user_id].to_i)
      expert_path = SearchExpertiseService.new(search: Search.last, user: user).report_most_likely_match.to_json
      render json: expert_path, status: 200
    else
      render json: { errors: 'Something went wrong, please try again' }, status: 400
    end
  end

  private
  def search_params
    params.require(:search).permit(:id, :search_text)
  end

  def permitted_params
    params.permit(:user_id, :search)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::ApiController
  def index
    render json: User.all, status: 200
  end

  def show
    render json: User.find(params[:id]), status: 200
  rescue => e
    render json: { errors: e }, status: 404
  end

  def create
    user = User.new(user_params)

    if user.save && UserExpertiseService.new(user).call
      render json: user, status: 200
    else
      render json: { errors: user.errors.full_messages }, status: 400
    end
  end

  private
  def user_params
    params.require(:user).permit(:id, :name, :url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tiny_urls_controller.rb
class TinyUrlsController < ApplicationController
  before_action :find_url

  def show
    redirect_to @url.sanitized_url
  end

  private

  def find_url
    @url = TinyUrl.find_by_shortened_url(params[:shortened_url])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  rescue => e
    render json: { errors: e }, status: 404
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EverlywellChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <footer>
    <%= javascript_pack_tag 'user_search' %>
    </footer>
  </body>

</html>

app/views/users/index.html.erb
<h1>Users#index</h1>
<table>
<tr><td>Name</td><td>website</td><td>Number of friends</td></tr>
<% @users.each do |user| %>
  <tr>
    <td><%= link_to user.name, user_path(user) %> </td>
    <td><%= user.url %> </td>
    <td><%= user.friends.count %> </td>
  </tr>
<% end %>
</table>

app/views/users/show.html.erb
<h1>
<%= @user.name %>
</h1>
</br>
<h3> Website </h3>
<h4> <%= @user.url %> </h4>
<%= link_to @user.tiny_url, tiny_urls_show_path(shortened_url: @user.tiny_url) %>
</br>
<h3> Current Expertise </h3>
<ul>
  <% if @user.expertise.empty? %>
    <h4> None Yet </h4>
  <% else @user.expertise.each do |exp| %>
      <li><%= exp.website_text.downcase.capitalize %></li>
    <% end %>
  <% end %>
</ul>
<h3> Current Friends </h3>
<ul>
  <% if @user.friends.empty? %>
    <h4> None Yet </h4>
  <% else @user.friends.each do |friend| %>
      <li><%= link_to friend.name, user_path(friend) %></li>
    <% end %>
  <% end %>
</ul>

<h2>Search Site Expertise for new Friend</h2>
<input id="searchInput" type="search" name="gsearch" data-userId="<%=@user.id%>" >
<button id="searchSubmit" type="submit">Search</button>
</br>
<div id="searchLoader" class="loader" style="display:none"></div>
</br>
<div id='searchList'>
<ul id='searchResults'>
</ul>
</div>